# Generated by Django 6.0.3 on 2026-04-04 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('racha_actual', models.PositiveIntegerField(default=0)),
                ('mejor_racha', models.PositiveIntegerField(default=0)),
                ('ultima_fecha', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desbloqueado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
