# Generated by Django 6.0.3 on 2026-04-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Admin')], default='usuario', max_length=20)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('moneda', models.CharField(default='PEN', max_length=10)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('xp_actual', models.PositiveIntegerField(default=0)),
                ('mejor_racha', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
